import { Inter } from "next/font/google";
import "./globals.css";

// Initializing Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Metadata for the page
export const metadata = {
  title: "Create Next App",  // Title of the application
  description: "Generated by create next app",  // Description of the application
};

// RootLayout component to wrap the entire application
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>  {/* Render children components with Inter font class */}
    </html>
  );
}
